# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.MORNING_STARS }}
         name: morningstars-obh\$morningstars-obh
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add azure git@https://morningstars-obh.scm.azurewebsites.net:443/morningstars-obh.git
        git config --global user.email "mohapatra_jyoti@optum.com"
        git config --global user.name "morningstars"
        git checkout main
        git push -u morningstars main
